#!/usr/bin/env python3
"""
configure.py — interactive setup for cambio rate alerts.

Asks which provider you want (Telegram by default, WhatsApp via Twilio
available), walks through provider-specific setup, captures the shared
threshold/cooldown, writes a mode-600 `.env`. Nothing sensitive is ever
committed.

Usage:
  python configure.py                  # interactive setup
  python configure.py --test           # send a test message using existing .env
  python configure.py --reset          # wipe .fx_alert.state (anchor + cooldown)
  python configure.py --force          # overwrite an existing .env
  python configure.py --provider telegram    # skip provider prompt
  python configure.py --find-chat-id   # re-detect chat_id using existing token
"""

import argparse
import getpass
import os
import sys
import time
from typing import Optional
from urllib.request import urlopen

import rate_alert
from notifiers import DEFAULT_PROVIDER, ENV_VAR, available, get_notifier
from notifiers.telegram import API_BASE, discover_chat_id

ENV_PATH = rate_alert.ENV_PATH
SANDBOX_FROM = "+14155238886"  # Twilio shared WhatsApp sandbox number


# ── terminal helpers ─────────────────────────────────────────────────────────
def _c(code: str, txt: str) -> str:
    return f"\033[{code}m{txt}\033[0m" if sys.stdout.isatty() else txt


def header(t: str) -> str:
    return _c("1;36", t)


def dim(t: str) -> str:
    return _c("2", t)


def ok(t: str) -> str:
    return _c("32", t)


def warn(t: str) -> str:
    return _c("33", t)


def err(t: str) -> str:
    return _c("31", t)


def section(title: str) -> None:
    print()
    print(_c("1", f"▸ {title}"))


# ── prompts ──────────────────────────────────────────────────────────────────
def ask(label: str, default: Optional[str] = None, hide: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            if hide:
                val = getpass.getpass(f"  {label}{suffix}: ").strip()
            else:
                val = input(f"  {label}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            sys.exit(1)
        if val:
            return val
        if default is not None:
            return default


def yes_no(label: str, default: bool = False) -> bool:
    suffix = "[S/n]" if default else "[s/N]"
    ans = ask(f"{label} {suffix}", default="s" if default else "n").lower()
    return ans.startswith("s") or ans.startswith("y")


def pause(label: str = "Pressione Enter quando terminar...") -> None:
    try:
        input(f"  {dim(label)}")
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(1)


# ── input validators ─────────────────────────────────────────────────────────
def is_valid_telegram_token(s: str) -> bool:
    """Bot tokens look like `<numeric_bot_id>:<35+ alphanum/-/_ chars>`."""
    parts = s.strip().split(":")
    return len(parts) == 2 and parts[0].isdigit() and len(parts[1]) >= 30


def is_valid_chat_id(s: str) -> bool:
    """Chat ids are signed integers — positive for users, negative for groups."""
    s = s.strip().lstrip("-")
    return s.isdigit() and 5 <= len(s) <= 16


# ── env IO ───────────────────────────────────────────────────────────────────
def write_env(values: dict, path: str = ENV_PATH) -> None:
    lines = [
        "# cambio — alert config",
        "# Generated by configure.py — DO NOT commit.",
        "",
    ]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(path, 0o600)


# ── provider setup flows ─────────────────────────────────────────────────────
def setup_telegram() -> dict:
    """Walk the user through @BotFather + auto chat_id discovery."""
    section("Configuração do Telegram")
    print(dim("    Mantenha o Telegram aberto no celular durante este setup."))
    print()
    print(_c("1", "    Passo 1 — Criar o bot"))
    print(
        "    • No Telegram, busque " + _c("1;36", "@BotFather") + " e abra a conversa"
    )
    print(f"    • Envie {_c('1', '/newbot')}")
    print('    • Escolha um nome (qualquer um, ex: "Cambio Alertas")')
    print(
        f"    • Escolha um username terminando em {_c('1', 'bot')}"
        ' (ex: "cambio_vitor_bot")'
    )
    print("    • O BotFather responde com um token tipo " + dim("1234567890:AAH..."))
    print()
    token = _prompt_token()
    chat_id = _prompt_chat_id(token)
    return {
        "NOTIFIER_PROVIDER": "telegram",
        "TELEGRAM_BOT_TOKEN": token,
        "TELEGRAM_CHAT_ID": chat_id,
    }


def _prompt_token() -> str:
    while True:
        token = ask("Cole o token aqui", hide=True)
        if is_valid_telegram_token(token):
            return token
        print(
            err(
                "    ✗ Isso não parece um token válido. "
                "Formato esperado: <numero>:<35+ caracteres>"
            )
        )
        print(dim("    Ex: 1234567890:AAH1234567890abcdefghijklmnopqrstuvwx"))


def _prompt_chat_id(token: str) -> str:
    """Try auto-discovery, fall back to validated manual input."""
    section("Passo 2 — Mandar uma mensagem pro bot")
    print(
        warn(
            "    ❗ ATENÇÃO: a mensagem deve ser enviada NO TELEGRAM (celular ou web),\n"
            "       NÃO aqui no terminal. Aqui você só dá Enter quando terminar."
        )
    )
    print()
    print("    • Abra o Telegram (celular ou " + _c("1;36", "web.telegram.org") + ")")
    print("    • Busque o username do bot que você acabou de criar")
    print("    • Mande qualquer mensagem pra ele (ex: " + _c("1", "oi") + ")")
    print("    • Volte aqui e pressione " + _c("1", "Enter"))
    pause("Enter quando tiver mandado a mensagem NO TELEGRAM...")

    # Limpa qualquer webhook que pode estar interceptando getUpdates
    _delete_webhook(token)

    chat_id = None
    for attempt in range(5):
        print(dim(f"    Buscando chat_id (tentativa {attempt + 1}/5)..."))
        chat_id = discover_chat_id(token)
        if chat_id:
            break
        time.sleep(2)

    if chat_id:
        print(f"    {ok('✓')} chat_id detectado: {ok(chat_id)}")
        if yes_no("Confirma usar esse chat?", default=True):
            return chat_id

    # manual fallback with validation
    print()
    print(warn("    ⚠  Vou pedir o chat_id manualmente."))
    print(
        dim(
            "    Pra achá-lo: abra no navegador (com a mensagem já enviada):\n"
            f"      {_c('1;36', f'https://api.telegram.org/bot{token[:12]}.../getUpdates')}\n"
            '    Procure por "chat":{"id":<NUMERO>} — esse número é o chat_id.'
        )
    )
    while True:
        candidate = ask("chat_id (só números)")
        if is_valid_chat_id(candidate):
            return candidate.strip()
        if ":" in candidate:
            print(
                err(
                    "    ✗ Isso parece o TOKEN do bot, não o chat_id. "
                    "O chat_id é só números."
                )
            )
        else:
            print(err("    ✗ chat_id inválido. Use apenas dígitos (ex: 123456789)."))


def _delete_webhook(token: str) -> None:
    """Some bots end up with a webhook set; that blocks getUpdates from returning."""
    try:
        url = f"{API_BASE.format(token=token)}/deleteWebhook"
        urlopen(url, timeout=5).read()
    except Exception:
        pass


def setup_whatsapp() -> dict:
    """Twilio WhatsApp setup — kept for the day WhatsApp becomes viable again."""
    section("Configuração do WhatsApp (via Twilio)")
    print(
        warn(
            "    ⚠  Requer conta Twilio. Se o sandbox da Twilio não atende,\n"
            "       você vai precisar de uma WABA via Meta — atualmente bloqueado\n"
            "       para muitos devs sem CNPJ. Considere Telegram."
        )
    )
    print()
    print(dim("    Telefone que vai receber os alertas (formato internacional)"))
    print(dim("    Exemplos: +55 11 91234-5678  ·  +55 21 99876-5432"))
    raw = ask("Número (com +)")
    digits = "".join(c for c in raw if c.isdigit())
    phone = f"+{digits}"
    print(f"    Vou enviar para: {ok(phone)}")
    if not yes_no("Confirma?", default=True):
        return setup_whatsapp()

    print()
    print(dim("    Twilio Account SID (https://console.twilio.com, começa com AC...)"))
    sid = ask("SID")
    print()
    print(dim("    Twilio Auth Token (input escondido)"))
    token = ask("Token", hide=True)
    print()
    print(dim(f"    Twilio 'From' WhatsApp. Sandbox: {SANDBOX_FROM}"))
    print(
        dim(
            "    Antes do 1º envio, mande 'join <duas-palavras>' do seu WhatsApp\n"
            "    para esse número — o código fica no console Twilio."
        )
    )
    raw_from = ask("From", default=SANDBOX_FROM)
    from_digits = "".join(c for c in raw_from if c.isdigit())
    twilio_from = f"+{from_digits}"

    return {
        "NOTIFIER_PROVIDER": "whatsapp",
        "TWILIO_ACCOUNT_SID": sid,
        "TWILIO_AUTH_TOKEN": token,
        "TWILIO_FROM": twilio_from,
        "WHATSAPP_TO": phone,
    }


_SETUP_FLOWS = {
    "telegram": setup_telegram,
    "whatsapp": setup_whatsapp,
}


def pick_provider(preselected: Optional[str] = None) -> str:
    if preselected:
        if preselected not in available():
            print(
                err(f"  ✗ provider '{preselected}' desconhecido. opções: {available()}")
            )
            sys.exit(1)
        return preselected

    section("Provedor de mensageria")
    print("  Escolha por onde receber os alertas:")
    print(
        f"    {_c('1;32', '1')}) Telegram   "
        + dim("grátis, ilimitado, oficial, 2-min setup  (recomendado)")
    )
    print(
        f"    {_c('1;33', '2')}) WhatsApp   "
        + dim("via Twilio — requer conta paga, sandbox limitado")
    )
    while True:
        choice = ask("Escolha", default="1")
        if choice in ("1", "telegram"):
            return "telegram"
        if choice in ("2", "whatsapp"):
            return "whatsapp"
        print(err(f"    ✗ opção inválida: {choice}"))


# ── flows ────────────────────────────────────────────────────────────────────
def run_setup(force: bool = False, provider: Optional[str] = None) -> None:
    print()
    print(header("  cambio · configuração de alertas"))
    print(dim("  ──────────────────────────────────"))
    print()
    print("  Configura alertas quando USD/BRL sobe além de um limite.")
    print("  Tudo salvo em " + _c("1", ".env") + " (já está no .gitignore).")

    if os.path.exists(ENV_PATH) and not force:
        print()
        print(warn(f"  ⚠  {ENV_PATH} já existe."))
        if not yes_no("  Sobrescrever?", default=False):
            print("  Abortado.")
            return

    chosen = pick_provider(provider)
    creds = _SETUP_FLOWS[chosen]()

    section("Threshold de alerta (% de alta para disparar)")
    print(dim("    Padrão 1.0% = avisa quando USD/BRL subir 1% desde o último alerta."))
    threshold = ask("Threshold %", default="1.0")

    section("Cooldown (minutos entre alertas)")
    print(dim("    Padrão 60 = no máximo 1 alerta por hora."))
    cooldown = ask("Cooldown (min)", default="60")

    values = {
        **creds,
        "FX_ALERT_THRESHOLD_PCT": threshold,
        "FX_ALERT_COOLDOWN_MIN": cooldown,
    }
    write_env(values)
    print()
    print(ok(f"  ✓ {ENV_PATH} criado (modo 600)."))

    print()
    if yes_no("  Enviar mensagem de teste agora?", default=True):
        rate_alert.load_env()
        notifier = get_notifier(chosen)
        ok_send, info = notifier.send(
            "🇧🇷 cambio · teste de configuração\n"
            "Se você está lendo isso, os alertas estão funcionando."
        )
        if ok_send:
            print(ok(f"  ✓ Mensagem enviada ({info}). Confere o app."))
        else:
            print(err(f"  ✗ Falhou: {info}"))

    print()
    print(header("  Próximos passos"))
    print("  Rodar com alertas:")
    print(
        _c("1;33", "    python fx_timing.py --lang pt --watch --notify --phone-alerts")
    )
    print()


def run_test() -> None:
    if not rate_alert.load_env():
        print(
            err(f"  ✗ {ENV_PATH} não encontrado. Rode `python configure.py` primeiro.")
        )
        sys.exit(1)
    provider = os.getenv(ENV_VAR, DEFAULT_PROVIDER)
    try:
        notifier = get_notifier(provider)
    except ValueError as e:
        print(err(f"  ✗ {e}"))
        sys.exit(1)
    if not notifier.is_configured():
        print(err(f"  ✗ Faltam env vars: {', '.join(notifier.missing_keys())}"))
        sys.exit(1)
    ok_send, info = notifier.send(
        f"🇧🇷 cambio · teste manual via {provider}\n"
        "Se você está lendo isso, o canal está OK."
    )
    if ok_send:
        print(ok(f"  ✓ enviado via {provider} ({info})."))
    else:
        print(err(f"  ✗ falhou: {info}"))
        sys.exit(1)


def run_reset() -> None:
    rate_alert.reset_state()
    print(ok(f"  ✓ estado do alerta reiniciado ({rate_alert.STATE_PATH} removido)."))


def run_find_chat_id() -> None:
    """Recovery flow: re-detect the Telegram chat_id and rewrite .env in place."""
    if not rate_alert.load_env():
        print(err(f"  ✗ {ENV_PATH} não encontrado. Rode `python configure.py`."))
        sys.exit(1)

    token = os.getenv("TELEGRAM_BOT_TOKEN")
    if not token:
        print(err("  ✗ TELEGRAM_BOT_TOKEN ausente no .env."))
        sys.exit(1)
    if not is_valid_telegram_token(token):
        print(err("  ✗ TELEGRAM_BOT_TOKEN tem formato inválido. Refaça o setup."))
        sys.exit(1)

    chat_id = _prompt_chat_id(token)
    _rewrite_env_key("TELEGRAM_CHAT_ID", chat_id)
    print()
    print(ok(f"  ✓ chat_id atualizado em {ENV_PATH}."))

    # reload + test
    os.environ["TELEGRAM_CHAT_ID"] = chat_id
    notifier = get_notifier("telegram")
    ok_send, info = notifier.send(
        "🇧🇷 cambio · chat_id corrigido. Alertas voltaram a funcionar."
    )
    if ok_send:
        print(ok(f"  ✓ mensagem de teste enviada ({info})."))
    else:
        print(err(f"  ✗ ainda falhou: {info}"))
        sys.exit(1)


def _rewrite_env_key(key: str, value: str, path: str = ENV_PATH) -> None:
    """Rewrite a single key in .env, preserving everything else."""
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    out = []
    found = False
    for line in lines:
        if line.strip().startswith(f"{key}="):
            out.append(f"{key}={value}\n")
            found = True
        else:
            out.append(line)
    if not found:
        out.append(f"{key}={value}\n")
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(out)
    os.chmod(path, 0o600)


def main() -> None:
    p = argparse.ArgumentParser(description="Configure cambio rate alerts.")
    p.add_argument("--test", action="store_true", help="Send a test message and exit.")
    p.add_argument("--reset", action="store_true", help="Wipe anchor + cooldown state.")
    p.add_argument("--force", action="store_true", help="Overwrite existing .env.")
    p.add_argument(
        "--find-chat-id",
        action="store_true",
        help="Re-detect the Telegram chat_id using the existing token in .env.",
    )
    p.add_argument(
        "--provider",
        choices=available(),
        help="Skip the provider prompt and go straight to setup.",
    )
    args = p.parse_args()

    if args.test:
        run_test()
    elif args.reset:
        run_reset()
    elif args.find_chat_id:
        run_find_chat_id()
    else:
        run_setup(force=args.force, provider=args.provider)


if __name__ == "__main__":
    main()
