#!/usr/bin/env python3
"""
configure.py — interactive setup for WhatsApp rate-spike alerts.

Asks for your phone, Twilio credentials, threshold and cooldown.
Writes a local .env (gitignored). Never commits your phone.

Usage:
  python configure.py            # interactive
  python configure.py --test     # send a test message using existing .env
  python configure.py --reset    # wipe .fx_whatsapp.state (anchor + cooldown)
  python configure.py --force    # overwrite an existing .env
"""

import argparse
import getpass
import os
import sys
from typing import Optional

import whatsapp

ENV_PATH = whatsapp.ENV_PATH
SANDBOX_FROM = "+14155238886"  # Twilio's shared WhatsApp sandbox number


# ── tiny terminal helpers ────────────────────────────────────────────────────
def _c(code: str, txt: str) -> str:
    return f"\033[{code}m{txt}\033[0m" if sys.stdout.isatty() else txt


def header(t: str) -> str:
    return _c("1;36", t)


def dim(t: str) -> str:
    return _c("2", t)


def ok(t: str) -> str:
    return _c("32", t)


def warn(t: str) -> str:
    return _c("33", t)


def err(t: str) -> str:
    return _c("31", t)


def section(title: str) -> None:
    print()
    print(_c("1", f"▸ {title}"))


# ── prompts ──────────────────────────────────────────────────────────────────
def ask(label: str, default: Optional[str] = None, hide: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            if hide:
                val = getpass.getpass(f"  {label}{suffix}: ").strip()
            else:
                val = input(f"  {label}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            sys.exit(1)
        if val:
            return val
        if default is not None:
            return default


def yes_no(label: str, default: bool = False) -> bool:
    suffix = "[S/n]" if default else "[s/N]"
    ans = ask(f"{label} {suffix}", default="s" if default else "n").lower()
    return ans.startswith("s") or ans.startswith("y")


def normalize_phone(raw: str) -> str:
    """Keep only digits, prefix with +."""
    digits = "".join(c for c in raw if c.isdigit())
    return f"+{digits}" if digits else ""


def prompt_phone() -> str:
    """Ask for the phone number with country code; loop until user confirms."""
    print(dim("    Use formato internacional: código país + DDD + número."))
    print(dim("    Exemplos: +55 11 91234-5678  ·  +55 21 99876-5432"))
    while True:
        raw = ask("Número (com +)")
        phone = normalize_phone(raw)
        if len(phone) < 11 or len(phone) > 16:
            print(err(f"    ✗ {phone or '(vazio)'} não parece válido. Tente de novo."))
            continue
        print(f"    Vou enviar para: {ok(phone)}")
        if yes_no("Confirma este número?", default=True):
            return phone


# ── env IO ───────────────────────────────────────────────────────────────────
def write_env(values: dict, path: str = ENV_PATH) -> None:
    lines = [
        "# cambio — WhatsApp alert config",
        "# Generated by configure.py — DO NOT commit.",
        "",
        "# Twilio (https://console.twilio.com)",
        f"TWILIO_ACCOUNT_SID={values['TWILIO_ACCOUNT_SID']}",
        f"TWILIO_AUTH_TOKEN={values['TWILIO_AUTH_TOKEN']}",
        f"TWILIO_FROM={values['TWILIO_FROM']}",
        "",
        "# Destination (your phone in E.164)",
        f"WHATSAPP_TO={values['WHATSAPP_TO']}",
        "",
        "# Alert rules",
        f"FX_ALERT_THRESHOLD_PCT={values['FX_ALERT_THRESHOLD_PCT']}",
        f"FX_ALERT_COOLDOWN_MIN={values['FX_ALERT_COOLDOWN_MIN']}",
        "",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(path, 0o600)  # rw owner only


# ── flows ────────────────────────────────────────────────────────────────────
def run_setup(force: bool = False) -> None:
    print()
    print(header("  cambio · configuração de alertas WhatsApp"))
    print(dim("  ────────────────────────────────────────────"))
    print()
    print("  Configura alertas WhatsApp quando USD/BRL sobe além de um limite.")
    print("  Tudo salvo em " + _c("1", ".env") + " (já está no .gitignore).")
    print(dim("  Estimativa: 2 minutos. Requer conta Twilio (free trial OK)."))

    if os.path.exists(ENV_PATH) and not force:
        print()
        print(warn(f"  ⚠  {ENV_PATH} já existe."))
        if not yes_no("  Sobrescrever?", default=False):
            print("  Abortado.")
            return

    section("Telefone que vai receber os alertas")
    phone = prompt_phone()

    section("Twilio Account SID")
    print(
        dim("    Achado em https://console.twilio.com (Account Info, começa com AC...)")
    )
    sid = ask("SID")

    section("Twilio Auth Token")
    print(dim("    Mesma página. Input fica escondido."))
    token = ask("Token", hide=True)

    section("Twilio 'From' (número WhatsApp da Twilio)")
    print(dim(f"    Para o sandbox use: {SANDBOX_FROM}"))
    print(dim("    Antes do 1º envio, mande 'join <duas-palavras>' do seu WhatsApp"))
    print(dim("    para esse número — o código fica no console Twilio."))
    twilio_from = normalize_phone(ask("From", default=SANDBOX_FROM))

    section("Threshold de alerta (% de alta para disparar)")
    print(dim("    Padrão 1.0% = avisa quando USD/BRL subir 1% desde o último alerta."))
    threshold = ask("Threshold %", default="1.0")

    section("Cooldown (minutos entre alertas)")
    print(dim("    Padrão 60 = no máximo 1 alerta por hora."))
    cooldown = ask("Cooldown (min)", default="60")

    values = {
        "TWILIO_ACCOUNT_SID": sid,
        "TWILIO_AUTH_TOKEN": token,
        "TWILIO_FROM": twilio_from,
        "WHATSAPP_TO": phone,
        "FX_ALERT_THRESHOLD_PCT": threshold,
        "FX_ALERT_COOLDOWN_MIN": cooldown,
    }
    write_env(values)
    print()
    print(ok(f"  ✓ {ENV_PATH} criado (modo 600)."))

    print()
    if yes_no("  Enviar mensagem de teste agora?", default=True):
        whatsapp.load_env()
        ok_send, info = whatsapp.send(
            "🇧🇷 cambio · teste de configuração\n"
            "Se você está lendo isso, os alertas estão funcionando."
        )
        if ok_send:
            print(ok(f"  ✓ Mensagem enviada ({info}). Confere o WhatsApp."))
        else:
            print(err(f"  ✗ Falhou: {info}"))
            print(dim("    Dicas:"))
            print(
                dim("    • No sandbox, você precisa primeiro mandar 'join <palavras>'")
            )
            print(dim("      do seu WhatsApp para o número Twilio (uma vez só)."))
            print(dim("    • Verifique se o SID e o token estão corretos."))
            print(dim("    • Verifique se o número de destino tem código do país."))

    print()
    print(header("  Próximos passos"))
    print("  Rodar com alertas:")
    print(_c("1;33", "    python fx_timing.py --lang pt --watch --notify --whatsapp"))
    print()


def run_test() -> None:
    if not whatsapp.load_env():
        print(
            err(f"  ✗ {ENV_PATH} não encontrado. Rode `python configure.py` primeiro.")
        )
        sys.exit(1)
    if not whatsapp.is_configured():
        print(err(f"  ✗ Faltam env vars: {', '.join(whatsapp.missing_keys())}"))
        sys.exit(1)
    msg = "🇧🇷 cambio · teste manual\nSe você está lendo isso, o canal está OK."
    ok_send, info = whatsapp.send(msg)
    if ok_send:
        print(ok(f"  ✓ enviado ({info})."))
    else:
        print(err(f"  ✗ falhou: {info}"))
        sys.exit(1)


def run_reset() -> None:
    whatsapp.reset_state()
    print(ok("  ✓ estado do alerta reiniciado (.fx_whatsapp.state removido)."))


def main() -> None:
    p = argparse.ArgumentParser(description="Configure WhatsApp alerts for cambio.")
    p.add_argument("--test", action="store_true", help="Send a test message and exit.")
    p.add_argument("--reset", action="store_true", help="Wipe anchor + cooldown state.")
    p.add_argument("--force", action="store_true", help="Overwrite existing .env.")
    args = p.parse_args()

    if args.test:
        run_test()
    elif args.reset:
        run_reset()
    else:
        run_setup(force=args.force)


if __name__ == "__main__":
    main()
