"""
Cambio monitor server — single command for API + UI.

  python server.py            API only on :8765
  python server.py --dev      API + Vite dev server (one command)

Endpoints:
  GET  /api/dashboard   — summary stats + last signals
  GET  /api/journal     — full journal
  GET  /api/state       — alert state (anchor, cooldown)
  GET  /api/thresholds  — current thresholds
  POST /api/thresholds  — update thresholds
  GET  /api/notifier    — phone alert config status
  POST /api/notifier    — configure phone alerts
  POST /api/notifier/test — send a test message
"""

import argparse
import json
import logging
import os
import signal
import subprocess
import sys
import time
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.request import Request, urlopen

import journal_db as journal
from notifiers import get_notifier
from notifiers.telegram import API_BASE

STATE_PATH = ".fx_alert.state"
THRESHOLDS_PATH = ".fx_thresholds.json"
ENV_PATH = ".env"

DEFAULT_THRESHOLDS = {
    "watch_interval_min": 5,
    "notify_threshold": 0.40,
    "notify_cooldown_hours": 6,
    "alert_threshold_pct": 1.0,
    "alert_cooldown_min": 5,
    "dca_floor": 0.25,
    "dca_ceiling": 0.75,
    "spread_bps": 50,
    "deadline_days": 15,
}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(message)s",
    datefmt="%H:%M:%S",
    stream=sys.stderr,
)
log = logging.getLogger("cambio")


# ── persistence ──────────────────────────────────────────────────────────────


def load_thresholds() -> dict:
    if os.path.exists(THRESHOLDS_PATH):
        try:
            with open(THRESHOLDS_PATH) as f:
                return {**DEFAULT_THRESHOLDS, **json.load(f)}
        except Exception:
            pass
    return dict(DEFAULT_THRESHOLDS)


def save_thresholds(thresholds: dict) -> bool:
    try:
        with open(THRESHOLDS_PATH, "w") as f:
            json.dump(thresholds, f, indent=2)
        return True
    except Exception:
        return False


def load_state() -> dict:
    if os.path.exists(STATE_PATH):
        try:
            with open(STATE_PATH) as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def load_env_values() -> dict:
    """Read key-value pairs from .env."""
    if not os.path.exists(ENV_PATH):
        return {}
    vals = {}
    with open(ENV_PATH, encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            vals[key.strip()] = val.strip().strip('"').strip("'")
    return vals


def write_env_values(values: dict) -> bool:
    """Write a dict to .env preserving existing secret keys not in `values`."""
    existing = load_env_values()
    existing.update(values)
    lines = [
        "# cambio — alert config",
        "# Generated by server.py — DO NOT commit.",
        "",
    ]
    for k, v in sorted(existing.items()):
        lines.append(f"{k}={v}")
    lines.append("")
    try:
        with open(ENV_PATH, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        os.chmod(ENV_PATH, 0o600)
        return True
    except Exception:
        return False


# ── notifier helpers ─────────────────────────────────────────────────────────


def _mask_token(token: str) -> str:
    if len(token) <= 12:
        return token[:4] + "****"
    return token[:8] + "****" + token[-4:]


def _test_telegram(token: str, chat_id: str) -> tuple[bool, str]:
    """Send a diagnostic message to verify the Telegram config."""
    try:
        url = f"{API_BASE.format(token=token)}/sendMessage"
        import urllib.parse

        payload = urllib.parse.urlencode(
            {"chat_id": chat_id, "text": "🇧🇷 cambio · teste de configuração ✓"}
        ).encode()
        req = Request(
            url,
            data=payload,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
        with urlopen(req, timeout=10) as resp:
            import json as _json

            data = _json.loads(resp.read())
            if data.get("ok"):
                return True, "mensagem enviada ✓"
            return False, data.get("description", "erro desconhecido")
    except Exception as e:
        return False, str(e)


def _discover_chat_id(token: str) -> str | None:
    """Try to auto-discover chat_id from recent messages."""
    try:
        url = f"{API_BASE.format(token=token)}/getUpdates"
        with urlopen(url, timeout=10) as resp:
            import json as _json

            data = _json.loads(resp.read())
        if not data.get("ok"):
            return None
        results = data.get("result") or []
        if not results:
            return None
        last = results[-1]
        msg = (
            last.get("message")
            or last.get("edited_message")
            or last.get("channel_post")
        )
        if not msg:
            return None
        chat = msg.get("chat") or {}
        chat_id = chat.get("id")
        return str(chat_id) if chat_id is not None else None
    except Exception:
        return None


# ── HTTP handler ─────────────────────────────────────────────────────────────


class CambioHandler(SimpleHTTPRequestHandler):
    start_time = time.time()

    def do_GET(self):
        if self.path == "/api/health":
            self._json(_health_check())
        elif self.path == "/api/journal":
            entries = journal.all_entries()
            self._json([_entry_dict(e) for e in entries])
        elif self.path == "/api/state":
            self._json(load_state())
        elif self.path == "/api/thresholds":
            self._json(load_thresholds())
        elif self.path == "/api/notifier":
            self._json(_notifier_status())
        elif self.path == "/api/dashboard":
            entries = journal.all_entries()
            last = entries[0] if entries else None
            notified = journal.notified_entries(10)
            self._json(
                {
                    "state": load_state(),
                    "thresholds": load_thresholds(),
                    "last_signal": _entry_dict(last) if last else None,
                    "recent_signals": [_entry_dict(e) for e in entries[:10]],
                    "total_signals": len(entries),
                    "total_alerts": len([e for e in entries if e.notified]),
                    "recent_alerts": [_entry_dict(e) for e in notified],
                }
            )
        else:
            self.send_error(404, "Not Found")

    def do_POST(self):
        if self.path == "/api/thresholds":
            self._handle_thresholds()
        elif self.path == "/api/notifier":
            self._handle_notifier_config()
        elif self.path == "/api/notifier/test":
            self._handle_notifier_test()
        else:
            self.send_error(404, "Not Found")

    def do_OPTIONS(self):
        self.send_response(200)
        self._set_cors()
        self.end_headers()

    def _handle_thresholds(self):
        body = self._read_body()
        try:
            updates = json.loads(body)
            current = load_thresholds()
            current.update(updates)
            ok = save_thresholds(current)
            self._json(
                {"ok": ok, "thresholds": current}
                if ok
                else {"ok": False, "error": "failed to save"}
            )
        except Exception as e:
            self._json({"ok": False, "error": str(e)}, status=400)

    def _handle_notifier_config(self):
        body = self._read_body()
        try:
            cfg = json.loads(body)
        except Exception:
            self._json({"ok": False, "error": "invalid JSON"}, status=400)
            return

        provider = cfg.get("provider", "telegram")
        values = {"NOTIFIER_PROVIDER": provider}
        if provider == "telegram":
            token = cfg.get("telegram_bot_token", "").strip()
            chat_id = cfg.get("telegram_chat_id", "").strip()
            if token:
                values["TELEGRAM_BOT_TOKEN"] = token
            if chat_id:
                values["TELEGRAM_CHAT_ID"] = chat_id
        write_env_values(values)
        # reload environment so notifiers module picks up changes
        for k, v in values.items():
            os.environ[k] = v
        self._json({"ok": True, "status": _notifier_status()})

    def _handle_notifier_test(self):
        env = load_env_values()
        provider = env.get("NOTIFIER_PROVIDER", "telegram")
        token = env.get("TELEGRAM_BOT_TOKEN", "")
        chat_id = env.get("TELEGRAM_CHAT_ID", "")
        if provider != "telegram" or not token or not chat_id:
            self._json(
                {"ok": False, "error": "Telegram não configurado — configure primeiro"},
                status=400,
            )
            return
        # Try auto-discovery if chat_id wasn't explicitly provided
        if chat_id == "auto":
            discovered = _discover_chat_id(token)
            if discovered:
                write_env_values({"TELEGRAM_CHAT_ID": discovered})
                os.environ["TELEGRAM_CHAT_ID"] = discovered
                chat_id = discovered
                self._json(
                    {
                        "ok": True,
                        "message": "chat_id descoberto automaticamente",
                        "chat_id": discovered,
                    }
                )
                return
            self._json(
                {
                    "ok": False,
                    "error": "Mande uma mensagem pro bot no Telegram primeiro",
                },
                status=400,
            )
            return
        ok, msg = _test_telegram(token, chat_id)
        self._json({"ok": ok, "message": msg})

    def _read_body(self) -> bytes:
        content_length = int(self.headers.get("Content-Length", 0))
        return self.rfile.read(content_length)

    def _json(self, data: dict | list, status=200):
        body = json.dumps(data, default=str).encode()
        self.send_response(status)
        self._set_cors()
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _set_cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def log_message(self, format, *args):
        log.info("%s", format % args)


def _health_check() -> dict:
    """System health — database, state, thresholds, uptime."""
    uptime = time.time() - CambioHandler.start_time
    checks = {"uptime_seconds": round(uptime, 1)}

    # database
    try:
        entries = journal.all_entries(1)
        checks["db"] = {"ok": True, "entries": len(journal.all_entries())}
        checks["last_signal_age_min"] = (
            round((time.time() - entries[0].ts.timestamp()) / 60, 1)
            if entries
            else None
        )
    except Exception as e:
        checks["db"] = {"ok": False, "error": str(e)}

    # state file
    checks["state"] = {"ok": os.path.exists(STATE_PATH)}

    # thresholds file
    try:
        load_thresholds()
        checks["thresholds"] = {"ok": True}
    except Exception as e:
        checks["thresholds"] = {"ok": False, "error": str(e)}

    # .env existence
    checks["env"] = {"ok": os.path.exists(ENV_PATH)}

    healthy = all(v.get("ok", v) if isinstance(v, dict) else v for v in checks.values())
    checks["healthy"] = healthy
    return checks


def _notifier_status() -> dict:
    env = load_env_values()
    provider = env.get("NOTIFIER_PROVIDER", "telegram")
    token = env.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = env.get("TELEGRAM_CHAT_ID", "")

    try:
        notifier = get_notifier(provider)
        is_configured = notifier.is_configured()
        missing = notifier.missing_keys()
    except Exception:
        is_configured = False
        missing = ["unknown provider"]

    return {
        "provider": provider,
        "is_configured": is_configured,
        "missing_keys": missing,
        "telegram_bot_token": _mask_token(token) if token else "",
        "telegram_chat_id": chat_id if chat_id else "",
        "has_token": bool(token),
        "has_chat_id": bool(chat_id),
    }


def _entry_dict(e: journal.Entry) -> dict:
    return {
        "ts": e.ts.isoformat(),
        "rate_signal": e.rate_signal,
        "rate_live": e.rate_live,
        "decision": e.decision,
        "size": e.size,
        "p_now": e.p_now,
        "p_split": e.p_split,
        "p_wait": e.p_wait,
        "composite": e.composite,
        "agreement": e.agreement,
        "regime": e.regime,
        "notified": e.notified,
        "executed": e.executed,
    }


# ── vite dev server ──────────────────────────────────────────────────────────


def start_vite(ui_dir: str) -> subprocess.Popen:
    log.info("starting vite dev server…")
    proc = subprocess.Popen(
        ["npm", "run", "dev", "--", "--host"],
        cwd=ui_dir,
        stdout=sys.stdout,
        stderr=sys.stderr,
        preexec_fn=os.setsid if sys.platform != "win32" else None,
    )
    time.sleep(3)
    if proc.poll() is not None:
        log.error("vite failed to start — run 'cd ui && npm install' first")
        sys.exit(1)
    return proc


def main():
    parser = argparse.ArgumentParser(description="Cambio monitor server")
    parser.add_argument("--port", type=int, default=8765, help="API port")
    parser.add_argument("--dev", action="store_true", help="Also start Vite dev server")
    args = parser.parse_args()

    ui_dir = os.path.join(os.path.dirname(__file__), "ui")
    vite_proc = None

    if args.dev:
        vite_proc = start_vite(ui_dir)
        log.info("vite running — http://localhost:5173")

    def cleanup(*_):
        log.info("shutting down…")
        if vite_proc:
            try:
                os.killpg(os.getpgid(vite_proc.pid), signal.SIGTERM)
            except Exception:
                vite_proc.terminate()
        sys.exit(0)

    signal.signal(signal.SIGINT, cleanup)
    signal.signal(signal.SIGTERM, cleanup)

    server = HTTPServer(("127.0.0.1", args.port), CambioHandler)
    log.info("api  running — http://127.0.0.1:%d", args.port)
    log.info("dashboard  / journal  / state  / thresholds  / notifier")
    if args.dev:
        log.info("open http://localhost:5173")
    log.info("Ctrl+C to stop\n")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        cleanup()


if __name__ == "__main__":
    main()
